### ISSUE TITLE
[Bug] Make Flatyplush Rounder

### ISSUE THREAD

**Issue by gabrielTach** [Fluufff/Website-issues#56]
**How to reproduce**
1. Login
2. Look at the avatar

**Description**
The Avatar looks flat (see flatyplush bellow)
![image](https://user-images.githubusercontent.com/6368290/168488480-805fd088-d6ed-4705-b022-8aa27e7c49ab.png)

It should be like that
![image](https://user-images.githubusercontent.com/6368290/168488906-dff4194b-c3bb-4046-ba22-ca9c3efb34a7.png)

**Problem**
Platyplush shouldn't be flatyplush.

**Notes**
- Firefox 100.0 Linux
- Maybe use something like:
```css
{
  display: inline-block;
  width: 35px;
  height: 35px;
  background-size: cover;
  background-position: center;
  border-radius: 50%;
}
```
And replace the `<img src="/assets/avatars/thumbnail_1.jpg">` by a `<div style="background-image: url(/assets/avatars/thumbnail_1.jpg);">`
